### PR TITLE
More changes to input validate

### PR DESCRIPTION
**Pull request by AbitFishy**
made a separate branch to stop interfering with Alex lol

### CODE REVIEW

**Comment by tkim013** [comment]
under issues, age validation:  typed in 3/4 and it keeps prompting me to input age infinitely.

**Comment by LightingWolf** [comment]
I like the date changes! I appreciate it, I was having a crap time trying to figure out the date stuff

**Comment by AbitFishy** [comment]
> under issues, age validation: typed in 3/4 and it keeps prompting me to input age infinitely.

#12

**Comment by tkim013** [comment]
Please choose a gender:  
 1. Male 
2. Female 
3. Prefer not to say

spacing error on 1 that was fixed on #8

**Comment by tkim013** [comment]
#15 valid input validation for time unknown.

**Pull request merged**
